---
- hosts: all
  gather_facts: true
  tasks:
    - name: Run tcib playbook
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook ci/playbooks/tcib/tcib.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/tcib.yml
          -e @scenarios/centos-9/zuul_inventory.yml
